namespace BattleBitAPI.Addons.EventHandler.Common;

public enum EventType
{
    OnPlayerConnected,
    OnAPlayerDownedAnotherPlayer,
    OnAPlayerRevivedAnotherPlayer,
    OnConnected,
    OnDisconnected,
    OnGameStateChanged,
    OnPlayerChangedRole,
    OnPlayerChangeTeam,
    OnPlayerDied,
    OnPlayerDisconnected,
    OnPlayerGivenUp,
    OnPlayerJoinSquad,
    OnPlayerJoiningToServer,
    OnPlayerLeftSquad,
    OnPlayerReported,
    OnPlayerRequestingToChangeRole,
    OnPlayerRequestingToChangeTeam,
    OnPlayerSpawned,
    OnPlayerSpawning,
    OnPlayerTypedMessage,
    OnReconnected,
    OnRoundEnded,
    OnRoundStarted,
    OnSavePlayerStats,
    OnTick,
    OnGameServerConnecting,
    OnValidateGameServerToken,
    OnGameServerConnected,
    OnGameServerReconnected,
    OnGameServerDisconnected,
    OnCreatingGameServerInstance,
    OnCreatingPlayerInstance
}