name: Deploy and publish
on:
  push:
    # paths:
    #   - 'Documentation/**.md'
    #   - 'Documentation/**.yml'
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore 
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore
        
    - run: dotnet tool update -g docfx
    - run: docfx Documentation/docfx.json
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: Documentation/_site
